# Generated by Django 4.0.3 on 2022-07-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('base', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Liberado', 'Liberado'), ('Pendente', 'Pendente')], max_length=100, null=True)),
                ('clinica', models.CharField(blank=True, choices=[('Clinica Sorriso', 'Clinica Sorriso'), ('SEPRI', 'SEPRI')], max_length=100, null=True)),
                ('realizacao_exame', models.DateField(blank=True, max_length=100, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('local_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='')),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('nib', models.CharField(max_length=100, null=True, unique=True)),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo'), ('Contratado', 'Contratado')], max_length=100)),
                ('nr_bi', models.CharField(max_length=100, null=True, unique=True)),
                ('sexo', models.CharField(max_length=100, null=True)),
                ('nuit', models.CharField(max_length=100, null=True)),
                ('inss', models.CharField(max_length=100, null=True)),
                ('data_nascimeto', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cracha',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=100)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colaborador')),
                ('validade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aso')),
            ],
        ),
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('botas', models.IntegerField(blank=True, null=True)),
                ('camisa', models.IntegerField(blank=True, null=True)),
                ('perneiras', models.IntegerField(blank=True, null=True)),
                ('capacetes', models.IntegerField(blank=True, null=True)),
                ('jugulares', models.IntegerField(blank=True, null=True)),
                ('abafadores', models.IntegerField(blank=True, null=True)),
                ('colete_refletor', models.IntegerField(blank=True, null=True)),
                ('oculos_de_protecao', models.IntegerField(blank=True, null=True)),
                ('Luvas', models.IntegerField(blank=True, null=True)),
                ('galochas', models.IntegerField(blank=True, null=True)),
                ('capas_de_chuva_refletores', models.IntegerField(blank=True, null=True)),
                ('lanterna', models.IntegerField(blank=True, null=True)),
                ('data_recepcao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='GestorProjecto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Rac',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.colaborador')),
                ('validade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aso')),
            ],
        ),
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('discricao', models.CharField(blank=True, max_length=500, null=True)),
                ('orcamento', models.FloatField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gestorprojecto')),
                ('membro', models.ManyToManyField(to='app.cracha')),
            ],
        ),
        migrations.CreateModel(
            name='MembroProjecto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('aso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aso')),
                ('cracha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cracha')),
                ('epi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.epi')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.colaborador')),
                ('rac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rac')),
            ],
        ),
        migrations.AddField(
            model_name='aso',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colaborador'),
        ),
    ]
